# -*- coding: utf-8 -*-
"""myLCS_DP

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sJq1fTCGscqZW18d_gzaERf7WKouNLHt
"""

import random
import sys

def rando(length=12):
    nucleotides = ['A', 'T', 'C', 'G']
    sequence= ''.join(random.choice(nucleotides) for _ in range(length))
    print(f"Randomly Generated DNA sequence: {sequence}")
    return sequence

def myLCS_DP(X, Y):
    M, N=len(X), len(Y)
    table=[[0 for _ in range(N+1)] for _ in range(M+1)]
    for i in range(1, M+1):
        table[i][0]=table[i-1][0]
    for j in range(1, N+1):
        table[0][j]=table[0][j-1]
    for i in range(1, M+1):
        for j in range(1, N+1):
            if X[i-1]==Y[j-1]:
                table[i][j]=table[i-1][j-1]+1
            else:
                table[i][j]=max(table[i-1][j], table[i][j-1])

    lcs_length = table[M][N]
    lcs = [""] * (lcs_length + 1)
    i, j = M, N

    while i > 0 and j > 0:
        if X[i - 1] == Y[j - 1]:
            lcs[lcs_length] = X[i - 1]
            i -= 1
            j -= 1
            lcs_length -= 1
        elif table[i - 1][j] > table[i][j - 1]:
            i -= 1
        else:
            j -= 1

    print("LCS Length:", len(lcs) - 1)
    print("LCS:", "".join(lcs[1:]))
    print('Intermediate table:')
    for row in table:
        print(row)
    return table

if __name__ == "__main__":

  if len(sys.argv) == 3:
      X, Y = sys.argv[1], sys.argv[2]
  elif len(sys.argv) == 2:
     n = int(sys.argv[1])
     X = rando(n)
     Y = rando(n)
  else:
      n = 12
      X = rando(n)
      Y = rando(n)


myLCS_DP(X, Y)