# -*- coding: utf-8 -*-
"""myLCS_Re

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tAIq1pe7chEOqPyrW0WFLNx2vUuy4qID
"""

import random
import sys

def rando(length=12):
    nucleotides = ['A', 'T', 'C', 'G']
    sequence= ''.join(random.choice(nucleotides) for _ in range(length))
    print(f"Randomly Generated DNA sequence: {sequence}")
    return sequence

def myLCS_Re(X, Y):
    def recursive(i, j):
        if i == 0 or j == 0:
            return 0
        elif X[i - 1] == Y[j - 1]:
            return 1 + recursive(i - 1, j - 1)
        else:
            return max(recursive(i - 1, j), recursive(i, j - 1))

    lcs_len = recursive(len(X), len(Y))

    print("LCS Length:", lcs_len)

if __name__ == "__main__":

  if len(sys.argv) == 3:
      X, Y = sys.argv[1], sys.argv[2]
  elif len(sys.argv) == 2:
     n = int(sys.argv[1])
     X = rando(n)
     Y = rando(n)
  else:
      n = 12
      X = rando(n)
      Y = rando(n)


myLCS_Re(X, Y)